version: '3'

services:
  mcp:
    container_name: mcp
    build: .
    ports:
      - "8005:8005"
    environment:
      # - MCP_API_KEY=${MCP_API_KEY:-test1234} # Not ready yet, need updates to mcp library. Can be done artificially for now.
      - FASTMCP_DEBUG=true
      - FASTMCP_LOG_LEVEL=DEBUG
    volumes:
      - .:/app
    restart: unless-stopped 

  interpreter:
    container_name: interpreter
    restart: unless-stopped
    image: promptengineers/interpreter:latest
    ports:
      - "8888:8888"
      - "8001:8000"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan
    entrypoint: ["sh", "-c", "start-notebook.sh --NotebookApp.token='' & uvicorn api:app --host 0.0.0.0 --port 8000"]
    volumes:
      - /tmp:/tmp