version: '3'

services:
  mcp:
    container_name: mcp
    build: .
    ports:
      - "8005:8005"
    environment:
      # - MCP_API_KEY=${MCP_API_KEY:-test1234} # Not ready yet, need updates to mcp library. Can be done artificially for now.
      - FASTMCP_DEBUG=true
      - FASTMCP_LOG_LEVEL=DEBUG
    volumes:
      - .:/app
    restart: unless-stopped 